# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BodyBankEnterpriseUIDemo' do
  platform :ios, '9.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'BodyBankEnterprise'

  # Pods for BodyBankEnterpriseUIDemo

  target 'BodyBankEnterpriseUIDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BodyBankEnterpriseUIDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BodyBankEnterpriseUI' do
  platform :ios, '9.0'
  use_frameworks!
  use_modular_headers!
  pod 'SwiftSpinner'
  pod 'Alertift'
  pod 'SimpleImageViewerNew'
  pod 'NVActivityIndicatorView'
  pod 'Kingfisher'
  pod 'AFDateHelper'
  pod 'SCPageViewController'
  pod 'BodyBankEnterprise'
end
